[package]
name = "unfuck-dir"
version = "0.2.0"
edition = "2024"
description = "Organize 'Downloads' and other file graveyards."
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities"]
exclude = ["CLAUDE.md", ".claude/"]
keywords = ["cli", "files", "organize", "downloads", "undo"]
repository = "https://github.com/dmalt/unfuck-dir"

[lib]
name = "unfk"

[[bin]]
name = "unfuck"
path = "src/main.rs"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.50", features = ["derive", "color"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[dev-dependencies]
tempfile = "3.27.0"
